/**
 * api.js — Centralised API layer
 *
 * Responsibilities:
 * 1. Prepend the base URL from the env variable VITE_API_URL.
 * 2. Attach the Idempotency-Key header on POST requests.
 * 3. Throw a structured ApiError so callers can distinguish network
 *    failures from server-side validation errors.
 */

const BASE_URL = import.meta.env.VITE_API_URL || 'http://localhost:3001';

export class ApiError extends Error {
  constructor(message, status, body) {
    super(message);
    this.name = 'ApiError';
    this.status = status;
    this.body = body;
  }
}

async function request(path, options = {}) {
  const url = `${BASE_URL}${path}`;
  let response;
  try {
    response = await fetch(url, {
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...(options.headers || {}),
      },
    });
  } catch (networkErr) {
    throw new ApiError('Network error — check your connection.', 0, null);
  }

  let body;
  try {
    body = await response.json();
  } catch {
    body = null;
  }

  if (!response.ok) {
    const message =
      body?.error ||
      (body?.errors?.[0]?.msg) ||
      `Request failed (${response.status})`;
    throw new ApiError(message, response.status, body);
  }

  return body;
}

/* ── Public API ─────────────────────────────────────────────── */

/**
 * Create a new expense.
 * @param {object} data — { amount, category, description, date }
 * @param {string} idempotencyKey — UUID generated by the client
 */
export async function createExpense(data, idempotencyKey) {
  return request('/expenses', {
    method: 'POST',
    headers: { 'Idempotency-Key': idempotencyKey },
    body: JSON.stringify(data),
  });
}

/**
 * Fetch expenses with optional filter + sort.
 * @param {{ category?: string, sort?: string }} params
 */
export async function fetchExpenses(params = {}) {
  const qs = new URLSearchParams();
  if (params.category) qs.set('category', params.category);
  if (params.sort)     qs.set('sort', params.sort);
  const query = qs.toString() ? `?${qs}` : '';
  return request(`/expenses${query}`);
}

/** Fetch all distinct categories that exist in the DB. */
export async function fetchCategories() {
  return request('/expenses/categories');
}
